### ISSUE TITLE
Scroll Error on template page

### ISSUE THREAD

**Issue by jgwentworth92** [NJIT-WIS/mywebclass-simulation#25]
**Describe the bug**
small UI bug. when scrolling on content page, when you get to the bottom. both section 3 and 4 will be highlighted

**To Reproduce**
1. Go to template page. 
2. Scroll to bottom
3. See error

**Expected behavior**
section 4 on navbar should be highlighted

**Screenshots**
![image](https://user-images.githubusercontent.com/95505687/227362009-aca86a66-b54c-4c8e-9fb9-3116ebcd07fb.png).

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kaw393939** [comment]
Thanks good catch I’ll fix it in the nex mt version It
